// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pophewwrpnscmeqpbqxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvcGhld3dycG5zY21lcXBicXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjM0MjcsImV4cCI6MjA2NjQ5OTQyN30.CslSAS9krh4oXmclre2GLWf_T9ymkiI83oN5rfQSsJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);